#include "ir_binary_ops.hpp"

IR_NODE_OVERRIDES_IMPL(IR_B_Add);
IR_NODE_OVERRIDES_IMPL(IR_B_Subtract);
IR_NODE_OVERRIDES_IMPL(IR_B_Multiply);
IR_NODE_OVERRIDES_IMPL(IR_B_Divide);
IR_NODE_OVERRIDES_IMPL(IR_B_Modulo);
IR_NODE_OVERRIDES_IMPL(IR_B_And);
IR_NODE_OVERRIDES_IMPL(IR_B_Or);
IR_NODE_OVERRIDES_IMPL(IR_B_Xor);
IR_NODE_OVERRIDES_IMPL(IR_B_Left_Shift);
IR_NODE_OVERRIDES_IMPL(IR_B_Right_Shift);
IR_NODE_OVERRIDES_IMPL(IR_B_Less_Than);
IR_NODE_OVERRIDES_IMPL(IR_B_Less_Than_Equals);
IR_NODE_OVERRIDES_IMPL(IR_B_Greater_Than);
IR_NODE_OVERRIDES_IMPL(IR_B_Greater_Than_Equals);
IR_NODE_OVERRIDES_IMPL(IR_B_Equals);
