#include "ir_primitives.hpp"

IR_NODE_OVERRIDES_IMPL(IR_Boolean);
IR_NODE_OVERRIDES_IMPL(IR_Char);
IR_NODE_OVERRIDES_IMPL(IR_Fixnum);
IR_NODE_OVERRIDES_IMPL(IR_Single);
IR_NODE_OVERRIDES_IMPL(IR_Double);
IR_NODE_OVERRIDES_IMPL(IR_Array);
IR_NODE_OVERRIDES_IMPL(IR_String);
